-> Definindo caminho do arquivo e criando o dataframe

In [1]:
from pathlib import Path
import pandas as pd

arq = Path(".").parent / "LinkedIn_RDB_three.csv"

data = pd.read_csv(arq)
data

,job_id,title,description,pay_period,work_type,job_location,applies,remote_allowed,views,level,sponsored,compensation,job_domain,company_id,ben_pack_id
0,903408693,Office Associate,Provide clerical and administrative support to...,YEARLY,Full-time,"Albany, GA",5,False,49,NaN,True,"$42,000.00",Administration,3894635,1.0
1,1029078768,Registered Nurse (RN) Vaccinator,United Staffing Solutions is partnering with o...,HOURLY,Part-time,"Muskegon, MI",0,False,4,NaN,False,"$104,000.00",Healthcare,61469,1.0
2,1657978824,"REMOTE STEEL BUILDING SALES MAKE $1,000 TO $30...","REMOTE WORK FROM HOME $1,000 TO $10,000 COMMIS...",MONTHLY,Contract,"Texas, United States",0,True,0,NaN,False,"$144,000.00",Other,89350959,1.0
3,2148434033,Contract Bilingual Recruiter,"Location: Phoenix, AZ 85006---- IN OFFICE JOB ...",YEARLY,Contract,"Phoenix, AZ",0,False,0,Associate,False,"$65,000.00",Human Resources,1082195,1.0
4,2148434586,"Manager, Salesforce Platform",Invitation Homes is a fast-paced evolving publ...,YEARLY,Full-time,"New Hampshire, United States",0,False,0,Mid-Senior level,False,"$170,976.00",Information Technology,2780388,113.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6323,3701373385,Sales Manager,"Sales ManagerTexas, US $60,000–$70,000OTE $250...",YEARLY,Full-time,"Texas, United States",7,True,56,Mid-Senior level,False,"$70,000.00",Business Development,18312164,1.0
6324,3701373427,Design Intern,Looking to redefine the skyline or to be a par...,HOURLY,Internship,"Miramar, FL",2,False,20,Mid-Senior level,False,"$49,691.20",Design,1321042,1.0
6325,3701373432,Continuous Improvement Specialist,Continuous Improvement Specialist Opportunity!...,YEARLY,Full-time,"Mississippi, United States",11,False,28,Mid-Senior level,True,"$200,000.00",Management,2121817,128.0
6326,3701373493,Sr. Bilingual Copywriter (Canadian French),Overview\nTHE ROLE:\nThe Senior Bilingual Copy...,YEARLY,Full-time,"Torrance, CA",4,False,29,Mid-Senior level,False,"$105,200.00",Marketing,5619,47.0
6327,3701373524,MRI Manager,Grade 105\nJob Type: Officer of Administration...,YEARLY,Full-time,"New York, NY",0,False,10,Mid-Senior level,False,"$135,000.00",Other,2623,NaN

-> Vendo alguns dados do dataframe

In [2]:
data.describe()

             job_id      applies        views    company_id  ben_pack_id
count  6.328000e+03  6328.000000  6328.000000  6.328000e+03  6327.000000
mean   3.692362e+09    15.309735    76.117415  9.854270e+06    31.136716
std    8.051121e+07    45.276299   173.798446  2.232414e+07    42.069630
min    9.034087e+08     0.000000     0.000000  1.009000e+03     1.000000
25%    3.693071e+09     0.000000     3.000000  1.105600e+04     1.000000
50%    3.697355e+09     2.000000    21.000000  1.659680e+05     1.000000
75%    3.699409e+09    11.000000    78.000000  4.822178e+06    49.000000
max    3.701374e+09  1420.000000  5656.000000  9.856222e+07   173.000000

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   str
 4   work_type       6328 non-null   str
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int64
 9   level           4520 non-null   str
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   str
 12  job_domain      6205 non-null   str
 13  company_id      6328 non-null   int64
 14  ben_pack_id     6327 non-null   float64
dtypes: bool(2), float64(1), int64(4), str(8)
memory usage: 655.2 KB

-> Verificando o tamanho do dataframe (com maior precisão)

In [4]:
data.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   str
 4   work_type       6328 non-null   str
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int64
 9   level           4520 non-null   str
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   str
 12  job_domain      6205 non-null   str
 13  company_id      6328 non-null   int64
 14  ben_pack_id     6327 non-null   float64
dtypes: bool(2), float64(1), int64(4), str(8)
memory usage: 47.1 MB

-> Verificando o tipo de variável de cada coluna (versão resumida)

In [5]:
data.dtypes

job_id              int64
title                 str
description           str
pay_period            str
work_type             str
job_location          str
applies             int64
remote_allowed       bool
views               int64
level                 str
sponsored            bool
compensation          str
job_domain            str
company_id          int64
ben_pack_id       float64
dtype: object

-> Verificando como está distribuida a coluna "pay_period"

In [6]:
data["pay_period"].value_counts()

pay_period
YEARLY     3839
HOURLY     2412
MONTHLY      77
Name: count, dtype: int64

-> Trocando valores em str por valores em int8, para reduzir o tamanho do arquivo do dataframe

In [7]:
data["pay_period"] = data["pay_period"].map({"HOURLY":1,"MONTHLY":2, "YEARLY":3}).astype("int8")
data["pay_period"].dtype

dtype('int8')

In [8]:
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   int8
 4   work_type       6328 non-null   str
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int64
 9   level           4520 non-null   str
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   str
 12  job_domain      6205 non-null   str
 13  company_id      6328 non-null   int64
 14  ben_pack_id     6327 non-null   float64
dtypes: bool(2), float64(1), int64(4), int8(1), str(7)
memory usage: 46.8 MB

-> Verificando a possibilidade de mexer na coluna "work_type"

In [9]:
data["work_type"].value_counts()

work_type
Full-time     5266
Contract       666
Part-time      298
Temporary       47
Internship      30
Other           21
Name: count, dtype: int64

In [10]:
data["work_type"] = data["work_type"].map({"Other":0, "Internship":1, "Temporary":2, "Part-time":3, "Contract":4, "Full-time":5}).astype("int8")
data["work_type"].dtype

dtype('int8')

In [11]:
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   int8
 4   work_type       6328 non-null   int8
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int64
 9   level           4520 non-null   str
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   str
 12  job_domain      6205 non-null   str
 13  company_id      6328 non-null   int64
 14  ben_pack_id     6327 non-null   float64
dtypes: bool(2), float64(1), int64(4), int8(2), str(6)
memory usage: 46.5 MB

-> Verificando se dá para trabalhar com a coluna "compensation"

In [12]:
data["compensation"].value_counts()

compensation
$100,000.00     156
$120,000.00     126
$80,000.00      106
$60,000.00      106
$150,000.00     101
               ...
$73,840.00        1
$176,670.00       1
$138,564.00       1
$20,063.00        1
$114,712.00       1
Name: count, Length: 1457, dtype: int64

-> Transformando as strings em números

In [13]:
data["compensation"] = data["compensation"].str.replace("$","").str.replace(",","")
data["compensation"] = pd.to_numeric(data["compensation"], errors="coerce").astype("Float32")
data["compensation"].dtype

Float32Dtype()

In [14]:
data["compensation"].describe()

count           6328.0
mean     109900.507812
std         76861.6875
min            10000.0
25%       57411.600586
50%            91300.0
75%           143800.0
max          1300000.0
Name: compensation, dtype: Float64

-> Reduzindo os valores, sem perder muita informação (ou mantendo o que mais importa), e comprimindo um pouco mais

In [15]:
data["compensation"] = data["compensation"]/100
data["compensation"] = data["compensation"].astype("float16")
data["compensation"].describe()

c:\Users\Administrator\Documents\Codigos\Treinamento SciTec Jr\Treinamento-Scitec-Jr---2026\.venv\Lib\site-packages\numpy\_core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
c:\Users\Administrator\Documents\Codigos\Treinamento SciTec Jr\Treinamento-Scitec-Jr---2026\.venv\Lib\site-packages\pandas\core\nanops.py:1037: RuntimeWarning: overflow encountered in cast
  result = result.astype(dtype, copy=False)

count     6328.00
mean          inf
std           inf
min        100.00
25%        574.25
50%        913.00
75%       1438.00
max      13000.00
Name: compensation, dtype: float64

In [16]:
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   int8
 4   work_type       6328 non-null   int8
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int64
 9   level           4520 non-null   str
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   float16
 12  job_domain      6205 non-null   str
 13  company_id      6328 non-null   int64
 14  ben_pack_id     6327 non-null   float64
dtypes: bool(2), float16(1), float64(1), int64(4), int8(2), str(5)
memory usage: 46.1 MB

-> Verifincando e já trabalhando com a coluna "views"

In [17]:
data["views"].describe()

count    6328.000000
mean       76.117415
std       173.798446
min         0.000000
25%         3.000000
50%        21.000000
75%        78.000000
max      5656.000000
Name: views, dtype: float64

In [18]:
data["views"] = data["views"].astype("int16")
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   int8
 4   work_type       6328 non-null   int8
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int16
 9   level           4520 non-null   str
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   float16
 12  job_domain      6205 non-null   str
 13  company_id      6328 non-null   int64
 14  ben_pack_id     6327 non-null   float64
dtypes: bool(2), float16(1), float64(1), int16(1), int64(3), int8(2), str(5)
memory usage: 46.1 MB

-> Verificando se dá para trabalhar com a coluna "ben_pack_id"

In [19]:
data["ben_pack_id"].describe()

count    6327.000000
mean       31.136716
std        42.069630
min         1.000000
25%         1.000000
50%         1.000000
75%        49.000000
max       173.000000
Name: ben_pack_id, dtype: float64

-> Verificando se só tem valores inteiros, apesar das variaveis serem do tipo float

In [20]:
for x in data["ben_pack_id"]:
    if x%1 != 0: print(x)

nan

In [21]:
data["ben_pack_id"] = data["ben_pack_id"].astype("UInt8")
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   int8
 4   work_type       6328 non-null   int8
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int16
 9   level           4520 non-null   str
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   float16
 12  job_domain      6205 non-null   str
 13  company_id      6328 non-null   int64
 14  ben_pack_id     6327 non-null   UInt8
dtypes: UInt8(1), bool(2), float16(1), int16(1), int64(3), int8(2), str(5)
memory usage: 46.0 MB

-> Verificando se dá para trabalhar no company_id e otimizando essa parte dos dados

In [22]:
data["company_id"].describe()

count    6.328000e+03
mean     9.854270e+06
std      2.232414e+07
min      1.009000e+03
25%      1.105600e+04
50%      1.659680e+05
75%      4.822178e+06
max      9.856222e+07
Name: company_id, dtype: float64

In [23]:
data["company_id"] = data["company_id"].astype("UInt32")
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   int8
 4   work_type       6328 non-null   int8
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int16
 9   level           4520 non-null   str
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   float16
 12  job_domain      6205 non-null   str
 13  company_id      6328 non-null   UInt32
 14  ben_pack_id     6327 non-null   UInt8
dtypes: UInt32(1), UInt8(1), bool(2), float16(1), int16(1), int64(2), int8(2), str(5)
memory usage: 46.0 MB

-> Verificando e trabalhando na coluna "level"

In [24]:
data["level"].value_counts()

level
Mid-Senior level    2124
Entry level         1378
Associate            613
Director             294
Executive             62
Internship            49
Name: count, dtype: int64

In [25]:
data["level"] = data["level"].map({"Internship":0, "Executive":1, "Director":2, "Associate":3, "Entry level":4, "Mid-Senior level":5}).astype("Int8")
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   int8
 4   work_type       6328 non-null   int8
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int16
 9   level           4520 non-null   Int8
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   float16
 12  job_domain      6205 non-null   str
 13  company_id      6328 non-null   UInt32
 14  ben_pack_id     6327 non-null   UInt8
dtypes: Int8(1), UInt32(1), UInt8(1), bool(2), float16(1), int16(1), int64(2), int8(2), str(4)
memory usage: 45.7 MB

In [26]:
data["job_domain"].describe()

count           6205
unique            35
top       Management
freq             806
Name: job_domain, dtype: object

-> Mostrando como os elementos serão associados por números e, depois, substituindo os elementos por números

In [27]:
coluna = data["job_domain"].astype("category").cat.categories
coluna = {key:elem for key,elem in enumerate(coluna)}
print(coluna)

{0: 'Accounting', 1: 'Administration', 2: 'Advertising', 3: 'Analysis', 4: 'Art', 5: 'Business Development', 6: 'Counseling', 7: 'Customer Service', 8: 'Design', 9: 'Distribution', 10: 'Education', 11: 'Engineering', 12: 'Finance', 13: 'General Business', 14: 'Healthcare', 15: 'Human Resources', 16: 'Information Technology', 17: 'Legal', 18: 'Management', 19: 'Manufacturing', 20: 'Marketing', 21: 'Other', 22: 'Product Management', 23: 'Production', 24: 'Project Management', 25: 'Public Relations', 26: 'Purchasing', 27: 'Quality Assurance', 28: 'Research', 29: 'Sales', 30: 'Science', 31: 'Strategy', 32: 'Supply Chain', 33: 'Training', 34: 'Writing'}

In [28]:
data["job_domain"] = data["job_domain"].astype("category").cat.codes.astype("int8")
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   int64
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   int8
 4   work_type       6328 non-null   int8
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int16
 9   level           4520 non-null   Int8
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   float16
 12  job_domain      6328 non-null   int8
 13  company_id      6328 non-null   UInt32
 14  ben_pack_id     6327 non-null   UInt8
dtypes: Int8(1), UInt32(1), UInt8(1), bool(2), float16(1), int16(1), int64(2), int8(3), str(3)
memory usage: 45.4 MB

-> Verificamos que cada elemento de job_id é único e que podemos otimizar essa parte o dataframe

In [29]:
data["job_id"].nunique()

6328

In [30]:
data["job_id"] = data["job_id"].astype("uint16")
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   uint16
 1   title           6328 non-null   str
 2   description     6328 non-null   str
 3   pay_period      6328 non-null   int8
 4   work_type       6328 non-null   int8
 5   job_location    6328 non-null   str
 6   applies         6328 non-null   int64
 7   remote_allowed  6328 non-null   bool
 8   views           6328 non-null   int16
 9   level           4520 non-null   Int8
 10  sponsored       6328 non-null   bool
 11  compensation    6328 non-null   float16
 12  job_domain      6328 non-null   int8
 13  company_id      6328 non-null   UInt32
 14  ben_pack_id     6327 non-null   UInt8
dtypes: Int8(1), UInt32(1), UInt8(1), bool(2), float16(1), int16(1), int64(1), int8(3), str(3), uint16(1)
memory usage: 45.3 MB

-> Considerando que a descrição do que cada um faz,bem como o titulo deles na empresa, não é tão relevante para a analise dos dados do dataframe, vou retirar essas partes. Ainda mais que, caso seja necessário, com o job_id podemos recuperar quem é cada indivíduo

In [31]:
data.pop("title")
data.pop("description")
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 6328 entries, 0 to 6327
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   uint16
 1   pay_period      6328 non-null   int8
 2   work_type       6328 non-null   int8
 3   job_location    6328 non-null   str
 4   applies         6328 non-null   int64
 5   remote_allowed  6328 non-null   bool
 6   views           6328 non-null   int16
 7   level           4520 non-null   Int8
 8   sponsored       6328 non-null   bool
 9   compensation    6328 non-null   float16
 10  job_domain      6328 non-null   int8
 11  company_id      6328 non-null   UInt32
 12  ben_pack_id     6327 non-null   UInt8
dtypes: Int8(1), UInt32(1), UInt8(1), bool(2), float16(1), int16(1), int64(1), int8(3), str(1), uint16(1)
memory usage: 564.7 KB

-> Como em job_location aparecem os estados dos Estados Unidos, se substituirmos eles pelos números, podemos otimizar ainda mais os dados

In [32]:
data = data.sort_values("job_location")
data

c:\Users\Administrator\Documents\Codigos\Treinamento SciTec Jr\Treinamento-Scitec-Jr---2026\.venv\Lib\site-packages\pandas\io\formats\format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()
c:\Users\Administrator\Documents\Codigos\Treinamento SciTec Jr\Treinamento-Scitec-Jr---2026\.venv\Lib\site-packages\pandas\io\formats\format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,job_id,pay_period,work_type,job_location,applies,remote_allowed,views,level,sponsored,compensation,job_domain,company_id,ben_pack_id
4383,35859,3,5,"Aberdeen Proving Ground, MD",2,False,17,<NA>,False,770.000,1,1403,6
3666,44774,3,5,"Aberdeen, MD",3,False,24,4,False,1426.000,16,4898,44
4864,41085,3,5,"Abilene, TX",1,False,3,5,False,1450.000,29,232761,44
2671,37710,1,3,"Addison, IL",0,False,2,<NA>,False,416.000,-1,30599146,1
4200,27356,3,5,"Addison, TX",2,False,33,<NA>,True,2080.000,24,1441,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5216,52164,3,5,"Yorkville, IL",0,False,3,2,True,2012.000,29,3570660,1
1215,45736,1,5,"Yountville, CA",0,False,4,3,False,478.500,18,165725,1
1240,46639,3,5,"Yuba City, CA",4,False,57,<NA>,False,800.000,5,2604972,25
2828,46196,3,5,"Yuma, AZ",0,False,0,4,False,907.500,11,11419,1
3995,6992,1,5,"Zachary, LA",0,False,0,4,True,249.625,18,77301,44

In [33]:
mapeamento_completo = {
    ".*Alabama.*": 1, ".*AL.*": 1, ".*Montgomery.*": 1,
    ".*Alaska.*": 2, ".*AK.*": 2, ".*Juneau.*": 2,
    ".*Arizona.*": 3, ".*AZ.*": 3, ".*Phoenix.*": 3,
    ".*Arkansas.*": 4, ".*AR.*": 4, ".*Little Rock.*": 4,
    ".*California.*": 5, ".*CA.*": 5, ".*Sacramento.*": 5,
    ".*Colorado.*": 6, ".*CO.*": 6, ".*Denver.*": 6,
    ".*Connecticut.*": 7, ".*CT.*": 7, ".*Hartford.*": 7,
    ".*Delaware.*": 8, ".*DE.*": 8, ".*Dover.*": 8,
    ".*Florida.*": 9, ".*FL.*": 9, ".*Tallahassee.*": 9,
    ".*Georgia.*": 10, ".*GA.*": 10, ".*Atlanta.*": 10,
    ".*Hawaii.*": 11, ".*HI.*": 11, ".*Honolulu.*": 11,
    ".*Idaho.*": 12, ".*ID.*": 12, ".*Boise.*": 12,
    ".*Illinois.*": 13, ".*IL.*": 13, ".*Springfield.*": 13,
    ".*Indiana.*": 14, ".*IN.*": 14, ".*Indianapolis.*": 14,
    ".*Iowa.*": 15, ".*IA.*": 15, ".*Des Moines.*": 15,
    ".*Kansas.*": 16, ".*KS.*": 16, ".*Topeka.*": 16,
    ".*Kentucky.*": 17, ".*KY.*": 17, ".*Frankfort.*": 17,
    ".*Louisiana.*": 18, ".*LA.*": 18, ".*Baton Rouge.*": 18,
    ".*Maine.*": 19, ".*ME.*": 19, ".*Augusta.*": 19,
    ".*Maryland.*": 20, ".*MD.*": 20, ".*Annapolis.*": 20,
    ".*Massachusetts.*": 21, ".*MA.*": 21, ".*Boston.*": 21,
    ".*Michigan.*": 22, ".*MI.*": 22, ".*Lansing.*": 22,
    ".*Minnesota.*": 23, ".*MN.*": 23, ".*St. Paul.*": 23,
    ".*Mississippi.*": 24, ".*MS.*": 24, ".*Jackson.*": 24,
    ".*Missouri.*": 25, ".*MO.*": 25, ".*Jefferson City.*": 25,
    ".*Montana.*": 26, ".*MT.*": 26, ".*Helena.*": 26,
    ".*Nebraska.*": 27, ".*NE.*": 27, ".*Lincoln.*": 27,
    ".*Nevada.*": 28, ".*NV.*": 28, ".*Carson City.*": 28,
    ".*New Hampshire.*": 29, ".*NH.*": 29, ".*Concord.*": 29,
    ".*New Jersey.*": 30, ".*NJ.*": 30, ".*Trenton.*": 30,
    ".*New Mexico.*": 31, ".*NM.*": 31, ".*Santa Fe.*": 31,
    ".*New York.*": 32, ".*NY.*": 32, ".*Albany.*": 32,
    ".*North Carolina.*": 33, ".*NC.*": 33, ".*Raleigh.*": 33,
    ".*North Dakota.*": 34, ".*ND.*": 34, ".*Bismarck.*": 34,
    ".*Ohio.*": 35, ".*OH.*": 35, ".*Columbus.*": 35,
    ".*Oklahoma.*": 36, ".*OK.*": 36, ".*Oklahoma City.*": 36,
    ".*Oregon.*": 37, ".*OR.*": 37, ".*Salem.*": 37,
    ".*Pennsylvania.*": 38, ".*PA.*": 38, ".*Harrisburg.*": 38,
    ".*Rhode Island.*": 39, ".*RI.*": 39, ".*Providence.*": 39,
    ".*South Carolina.*": 40, ".*SC.*": 40, ".*Columbia.*": 40,
    ".*South Dakota.*": 41, ".*SD.*": 41, ".*Pierre.*": 41,
    ".*Tennessee.*": 42, ".*TN.*": 42, ".*Nashville.*": 42,
    ".*Texas.*": 43, ".*TX.*": 43, ".*Austin.*": 43,
    ".*Utah.*": 44, ".*UT.*": 44, ".*Salt Lake City.*": 44,
    ".*Vermont.*": 45, ".*VT.*": 45, ".*Montpelier.*": 45,
    ".*Virginia.*": 46, ".*VA.*": 46, ".*Richmond.*": 46,
    ".*Washington.*": 47, ".*WA.*": 47, ".*Olympia.*": 47,
    ".*West Virginia.*": 48, ".*WV.*": 48, ".*Charleston.*": 48,
    ".*Wisconsin.*": 49, ".*WI.*": 49, ".*Madison.*": 49,
    ".*Wyoming.*": 50, ".*WY.*": 50, ".*Cheyenne.*": 50,

    "Buffalo-Niagara Falls Area": 32,
    "Bowling Green Metropolitan Area": 17,
    "Charlotte Metro": 33,
    "Cincinnati Metropolitan Area": 35,
    "Dallas-Fort Worth Metroplex": 4,
    "Detroit Metropolitan Area": 22,
    "Erie-Meadville Area": 38,
    "Fargo-Moorhead": 34,
    "Grand Rapids Metropolitan Area": 22,
    # Maine (Estado 19)
    ".*Greater Bangor Area.*": 19,
    
    # Indiana (Estado 14)
    ".*Greater Bloomington Area.*": 14,
    
    # Tennessee (Estado 42)
    ".*Greater Chattanooga.*": 42,
    
    # Illinois (Estado 13)
    ".*Greater Chicago Area.*": 13,
    
    # Ohio (Estado 35)
    ".*Greater Cleveland.*": 35,
    
    # Texas (Estado 43)
    ".*Greater Corpus Christi Area.*": 43,
    ".*Greater Houston.*": 43,
    
    # Colorado (Estado 6)
    ".*Greater Fort Collins Area.*": 6,
    
    # Georgia (Estado 10)
    ".*Greater Macon.*": 10,
    
    # Florida (Estado 9)
    ".*Greater Orlando.*": 9,
    
    # Caso apareça apenas o país (Você pode definir um número padrão, ex: 0 ou None)
    ".*United States.*": 0,
    ".*Greater Philadelphia.*": 38,
    ".*Greater Pittsburgh Region.*": 38,
    ".*Greater Scranton Area.*": 38,
    
    # Washington (Estado 47)
    ".*Greater Seattle Area.*": 47,
    
    # Missouri (Estado 25) - Nota: St. Louis fica majoritariamente em MO
    ".*Greater St. Louis.*": 25,
    
    # Florida (Estado 9)
    ".*Greater Tampa Bay Area.*": 9,
    
    # Virginia (Estado 46)
    ".*Harrisonburg-Staunton-Waynesboro Area.*": 46,
    
    # Tennessee (Estado 42)
    ".*Knoxville Metropolitan Area.*": 42,
    
    # Nevada (Estado 28)
    ".*Las Vegas Metropolitan Area.*": 28,
    
    # California (Estado 5)
    ".*Los Angeles Metropolitan Area.*": 5,
    ".*San Francisco Bay Area.*": 5,
    ".*Memphis Metropolitan Area.*": 42,
    
    # Florida (Estado 9)
    ".*Miami-Fort Lauderdale Area.*": 9,
    ".*Pensacola Metropolitan Area.*": 9,
    
    # Alabama (Estado 1)
    ".*Mobile Metropolitan Area.*": 1,
    
    # Colorado (Estado 6)
    ".*Pueblo-Cañon City Area.*": 6,
    
    # California (Estado 5)
    ".*San Diego Metropolitan Area.*": 5
    
}

data["job_location"] = data["job_location"].replace(mapeamento_completo, regex=True).astype("int8")
data.info(memory_usage="deep")

<class 'pandas.DataFrame'>
Index: 6328 entries, 4383 to 3995
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   job_id          6328 non-null   uint16
 1   pay_period      6328 non-null   int8
 2   work_type       6328 non-null   int8
 3   job_location    6328 non-null   int8
 4   applies         6328 non-null   int64
 5   remote_allowed  6328 non-null   bool
 6   views           6328 non-null   int16
 7   level           4520 non-null   Int8
 8   sponsored       6328 non-null   bool
 9   compensation    6328 non-null   float16
 10  job_domain      6328 non-null   int8
 11  company_id      6328 non-null   UInt32
 12  ben_pack_id     6327 non-null   UInt8
dtypes: Int8(1), UInt32(1), UInt8(1), bool(2), float16(1), int16(1), int64(1), int8(4), uint16(1)
memory usage: 228.6 KB

# Espero ter otimizado o bastante agora ^_^

In [34]:
data = data.sort_values("job_id")
caminho = Path(".").parent/"arquivo_otimizado.csv"
data.to_csv(path_or_buf=caminho,sep=",",index=False)